#!/usr/bin/env python3
"""
data_to_maps.py

Convert the IceCube 10-year public point-source event sample (2008–2018) into
multi-energy HEALPix counts maps suitable for map-based SBI and OOD tests.

This script is intentionally conservative:
- It makes *counts* maps (no exposure correction, no unfolding).
- It does *not* apply masking by default (Capel+2020 reproduction baseline).
- It streams CSVs in chunks to avoid high memory use.

Expected data-release layout (after extracting the IceCube zip):
<DATA_DIR>/
  icecube_10year_ps/
    events/
      IC40_exp.csv
      IC59_exp.csv
      IC79_exp.csv
      IC86_I_exp.csv
      IC86_II_exp.csv
      IC86_III_exp.csv
      IC86_IV_exp.csv
      IC86_V_exp.csv
      IC86_VI_exp.csv
      IC86_VII_exp.csv
    uptime/
      IC40_exp.csv
      ...
    irfs/
      ...

Primary columns used (as provided in the release):
- "RA[deg]"   : reconstructed right ascension (J2000) in degrees
- "Dec[deg]"  : reconstructed declination (J2000) in degrees
- "log10(E/GeV)" : reconstructed muon-track energy proxy (log10 GeV)

The output is an .npz with:
- counts_map : int64 array, shape (n_bins, n_pix)
- E_edges_GeV: float array, bin edges in GeV
- nside, nest
- seasons, per-season event counts, and (optional) livetimes from uptime files

References:
- IceCube 10-year public point-source data release (2008–2018):
  https://icecube.wisc.edu/data-releases/2021/01/all-sky-point-source-icecube-data-years-2008-2018/
- SkyLLH dataset definition shows canonical filenames and the expected subfolder structure:
  https://icecube.github.io/skyllh/master/html/tutorials/publicdata_ps.html
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Sequence, Tuple

import numpy as np

try:
    import healpy as hp
except Exception as e:  # pragma: no cover
    hp = None

try:
    import pandas as pd
except Exception as e:  # pragma: no cover
    pd = None


DEFAULT_DATA_DIR = "/mnt/my-ssd/Data_for_IceCube_Population_Project"
DEFAULT_RELEASE_SUBDIR = "icecube_10year_ps"

DEFAULT_SEASONS = [
    "IC40",
    "IC59",
    "IC79",
    "IC86_I",
    "IC86_II",
    "IC86_III",
    "IC86_IV",
    "IC86_V",
    "IC86_VI",
    "IC86_VII",
]


def _require_healpy() -> None:
    if hp is None:
        raise RuntimeError(
            "healpy is required for map binning. Install with `pip install healpy` "
            "(and system HEALPix deps if needed)."
        )


def _require_pandas() -> None:
    if pd is None:
        raise RuntimeError("pandas is required for reading IceCube release tables. Install with `pip install pandas`.")


def read_real_map_metadata(npz_path: Path) -> Dict[str, Any]:
    """
    Load metadata from a .npz file generated by build_maps(...).

    Returns a dict with:
      - nside: int
      - nest: bool
      - E_edges_GeV: np.ndarray[float]
      - seasons_found: np.ndarray[str]
      - season_livetime_days: np.ndarray[float]
      - livetime_days_total: float (NaN-safe sum)
      - livetime_years_total: float (days / 365.25)
    """
    npz_path = Path(npz_path).expanduser().resolve()
    if not npz_path.exists():
        raise FileNotFoundError(f"Real-map NPZ not found: {npz_path}")

    with np.load(npz_path) as data:
        required = ("nside", "nest", "E_edges_GeV", "seasons_found", "season_livetime_days")
        missing = [k for k in required if k not in data]
        if missing:
            raise KeyError(f"NPZ missing keys {missing}: {npz_path}")

        nside = int(np.asarray(data["nside"]).item())
        nest = bool(np.asarray(data["nest"]).item())
        E_edges_GeV = np.asarray(data["E_edges_GeV"], dtype=float)

        seasons_raw = np.asarray(data["seasons_found"])
        seasons_found = np.asarray([str(s) for s in seasons_raw.tolist()], dtype=str)

        season_livetime_days = np.asarray(data["season_livetime_days"], dtype=float)
        livetime_days_total = float(np.nansum(season_livetime_days))
        livetime_years_total = float(livetime_days_total / 365.25)

    return {
        "nside": nside,
        "nest": nest,
        "E_edges_GeV": E_edges_GeV,
        "seasons_found": seasons_found,
        "season_livetime_days": season_livetime_days,
        "livetime_days_total": livetime_days_total,
        "livetime_years_total": livetime_years_total,
    }


def read_real_map_summary_json(summary_json_path: Path) -> Dict[str, Any]:
    """
    Parse sidecar summary JSON and return the same metadata keys as read_real_map_metadata(...),
    whenever the required fields are present.
    """
    summary_json_path = Path(summary_json_path).expanduser().resolve()
    if not summary_json_path.exists():
        raise FileNotFoundError(f"Summary JSON not found: {summary_json_path}")

    obj = json.loads(summary_json_path.read_text(encoding="utf-8"))
    global_obj = obj.get("global", obj)
    notes_obj = obj.get("notes", {})

    nside = global_obj.get("nside", obj.get("nside"))
    nest = global_obj.get("nest", obj.get("nest"))
    E_edges = obj.get("E_edges_GeV", notes_obj.get("energy_edges_GeV", global_obj.get("E_edges_GeV")))

    if nside is None or nest is None or E_edges is None:
        raise KeyError(
            "Summary JSON does not contain enough metadata keys. "
            "Expected nside, nest, and E_edges_GeV (or notes.energy_edges_GeV)."
        )

    season_lt_obj = obj.get("season_livetime_days", global_obj.get("season_livetime_days"))
    if isinstance(season_lt_obj, dict):
        seasons_found = np.asarray([str(k) for k in season_lt_obj.keys()], dtype=str)
        season_livetime_days = np.asarray([float(v) for v in season_lt_obj.values()], dtype=float)
    elif season_lt_obj is not None:
        season_livetime_days = np.asarray(season_lt_obj, dtype=float)
        seasons_found = np.asarray(
            [str(s) for s in global_obj.get("seasons_found", obj.get("seasons_found", []))],
            dtype=str,
        )
    else:
        seasons_found = np.asarray([str(s) for s in global_obj.get("seasons_found", obj.get("seasons_found", []))], dtype=str)
        season_livetime_days = np.full(seasons_found.size, np.nan, dtype=float)

    livetime_days_total = global_obj.get("livetime_days_total")
    if livetime_days_total is None:
        livetime_days_total = float(np.nansum(season_livetime_days))
    else:
        livetime_days_total = float(livetime_days_total)

    livetime_years_total = float(livetime_days_total / 365.25)

    return {
        "nside": int(nside),
        "nest": bool(nest),
        "E_edges_GeV": np.asarray(E_edges, dtype=float),
        "seasons_found": np.asarray(seasons_found, dtype=str),
        "season_livetime_days": np.asarray(season_livetime_days, dtype=float),
        "livetime_days_total": livetime_days_total,
        "livetime_years_total": livetime_years_total,
    }


def _parse_energy_edges(edges_str: Optional[str]) -> np.ndarray:
    """
    Parse energy edges. Supported formats:
    - comma-separated list: "1e4,3e4,1e5,3e5,1e6,3e6,1e7"
    - logspace shorthand:   "logspace:4,7,6"  -> np.logspace(4, 7, 6) in GeV
    """
    if edges_str is None or edges_str.strip() == "":
        return np.logspace(4.0, 7.0, 6)

    s = edges_str.strip()
    if s.startswith("logspace:"):
        payload = s.split("logspace:", 1)[1]
        parts = [p.strip() for p in payload.split(",")]
        if len(parts) != 3:
            raise ValueError("logspace format must be 'logspace:<log10 Emin>,<log10 Emax>,<n_edges>'")
        lo, hi, n = float(parts[0]), float(parts[1]), int(parts[2])
        if n < 2:
            raise ValueError("n_edges must be >= 2")
        return np.logspace(lo, hi, n)

    parts = [p.strip() for p in s.split(",") if p.strip()]
    if len(parts) < 2:
        raise ValueError("Need at least two edges.")
    edges = np.array([float(x) for x in parts], dtype=float)
    if not np.all(np.diff(edges) > 0):
        raise ValueError("Energy edges must be strictly increasing.")
    return edges


def _ensure_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _find_release_root(data_dir: Path, release_subdir: str = DEFAULT_RELEASE_SUBDIR) -> Path:
    direct = data_dir / release_subdir
    if direct.exists() and direct.is_dir():
        return direct

    for child in data_dir.iterdir():
        if child.is_dir():
            cand = child / release_subdir
            if cand.exists() and cand.is_dir():
                return cand

    raise FileNotFoundError(
        f"Could not find extracted release folder '{release_subdir}' under data_dir={data_dir}."
    )


def _maybe_unzip(zip_path: Path, data_dir: Path, force: bool = False) -> None:
    if not zip_path.exists():
        raise FileNotFoundError(f"Zip not found: {zip_path}")

    expected = data_dir / DEFAULT_RELEASE_SUBDIR
    if expected.exists() and not force:
        print(f"[info] {expected} already exists; skipping unzip. Use --force-unzip to override.")
        return

    print(f"[info] Extracting {zip_path} -> {data_dir} ...")
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(path=data_dir)
    print("[info] Extraction complete.")


def _resolve_columns(df: "pd.DataFrame") -> Tuple[str, str, str, Optional[str], Optional[str]]:
    cols = list(df.columns)

    def pick(candidates: Sequence[str]) -> Optional[str]:
        for c in candidates:
            if c in cols:
                return c
        lower = {c.lower(): c for c in cols}
        for c in candidates:
            if c.lower() in lower:
                return lower[c.lower()]
        return None

    ra_col = pick(["RA[deg]", "RA", "ra", "ra_deg"])
    dec_col = pick(["Dec[deg]", "DEC[deg]", "Dec", "dec", "dec_deg"])
    loge_col = pick(["log10(E/GeV)", "logE", "log10E", "log10_E_GeV", "log10(E)"])
    mjd_col = pick(["MJD[days]", "MJD", "Time", "time"])
    angerr_col = pick(["AngErr[deg]", "Error_Radius", "angErr", "sigma", "angerr_deg"])

    missing = [name for name, val in [("RA", ra_col), ("Dec", dec_col), ("log10(E/GeV)", loge_col)] if val is None]
    if missing:
        raise KeyError(
            f"Missing required columns {missing}. Found columns: {cols[:30]}{'...' if len(cols) > 30 else ''}"
        )
    return ra_col, dec_col, loge_col, mjd_col, angerr_col


def _season_event_filename(season: str) -> str:
    return f"{season}_exp.csv"


def _season_uptime_filename(season: str) -> str:
    return f"{season}_exp.csv"


def _read_tabular_csv(path: Path, *, nrows: Optional[int] = None, chunksize: Optional[int] = None):
    """
    Read IceCube public-release tables in either:
    - commented-header + whitespace-delimited format (release default), or
    - standard comma-separated CSV.
    """
    _require_pandas()
    first_nonempty = ""
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                first_nonempty = line.strip()
                break

    if first_nonempty.startswith("#"):
        header_line = first_nonempty.lstrip("#").strip()
        cols = re.split(r"\s+", header_line)
        return pd.read_csv(
            path,
            sep=r"\s+",
            engine="python",
            comment="#",
            names=cols,
            header=None,
            nrows=nrows,
            chunksize=chunksize,
        )

    return pd.read_csv(path, nrows=nrows, chunksize=chunksize)


def _load_livetime_days(uptime_csv: Path) -> float:
    _require_pandas()
    if not uptime_csv.exists():
        return float("nan")
    df = _read_tabular_csv(uptime_csv)
    start_col = None
    stop_col = None
    for c in df.columns:
        if c.lower().startswith("mjd_start"):
            start_col = c
        if c.lower().startswith("mjd_stop"):
            stop_col = c
    if start_col is None or stop_col is None:
        return float("nan")
    dt = df[stop_col].to_numpy(dtype=float) - df[start_col].to_numpy(dtype=float)
    dt = dt[np.isfinite(dt)]
    return float(np.sum(dt))


@dataclass(frozen=True)
class MapBuildConfig:
    nside: int
    nest: bool
    energy_edges_GeV: np.ndarray
    chunk_size: int
    seasons: Tuple[str, ...]


def _bin_events_to_map(csv_path: Path, cfg: MapBuildConfig) -> Tuple[np.ndarray, Dict[str, float]]:
    _require_healpy()
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing events file: {csv_path}")

    n_bins = len(cfg.energy_edges_GeV) - 1
    n_pix = hp.nside2npix(cfg.nside)
    counts_map = np.zeros((n_bins, n_pix), dtype=np.int64)

    n_total = 0
    n_used = 0
    per_bin = np.zeros(n_bins, dtype=np.int64)

    preview = _read_tabular_csv(csv_path, nrows=5)
    ra_col, dec_col, loge_col, _, _ = _resolve_columns(preview)

    for chunk in _read_tabular_csv(csv_path, chunksize=cfg.chunk_size):
        n_total += len(chunk)

        ra = chunk[ra_col].to_numpy(dtype=float)
        dec = chunk[dec_col].to_numpy(dtype=float)
        loge = chunk[loge_col].to_numpy(dtype=float)

        m = np.isfinite(ra) & np.isfinite(dec) & np.isfinite(loge)
        if not np.any(m):
            continue
        ra = ra[m]
        dec = dec[m]
        loge = loge[m]

        E = np.power(10.0, loge)
        b = np.searchsorted(cfg.energy_edges_GeV, E, side="right") - 1
        inrange = (b >= 0) & (b < n_bins)
        if not np.any(inrange):
            continue

        ra = ra[inrange]
        dec = dec[inrange]
        b = b[inrange].astype(np.int64)

        theta = np.deg2rad(90.0 - dec)
        phi = np.deg2rad(ra % 360.0)
        pix = hp.ang2pix(cfg.nside, theta, phi, nest=cfg.nest)

        for bi in range(n_bins):
            sel = (b == bi)
            if not np.any(sel):
                continue
            np.add.at(counts_map[bi], pix[sel], 1)
            c = int(np.sum(sel))
            per_bin[bi] += c
            n_used += c

    summary = {
        "n_events_total": float(n_total),
        "n_events_used_in_energy_range": float(n_used),
    }
    for i in range(n_bins):
        summary[f"n_events_bin_{i}"] = float(per_bin[i])
        summary[f"Ebin_{i}_GeV_lo"] = float(cfg.energy_edges_GeV[i])
        summary[f"Ebin_{i}_GeV_hi"] = float(cfg.energy_edges_GeV[i + 1])
    return counts_map, summary


def build_maps(
    release_root: Path,
    output_npz: Path,
    nside: int = 64,
    nest: bool = False,
    energy_edges_GeV: Optional[np.ndarray] = None,
    seasons: Optional[Sequence[str]] = None,
    chunk_size: int = 1_000_000,
    per_season: bool = False,
) -> None:
    _require_healpy()
    _require_pandas()
    if energy_edges_GeV is None:
        energy_edges_GeV = np.logspace(4.0, 7.0, 6)
    if seasons is None:
        seasons = list(DEFAULT_SEASONS)

    cfg = MapBuildConfig(
        nside=int(nside),
        nest=bool(nest),
        energy_edges_GeV=np.asarray(energy_edges_GeV, dtype=float),
        chunk_size=int(chunk_size),
        seasons=tuple(seasons),
    )

    events_dir = release_root / "events"
    uptime_dir = release_root / "uptime"
    if not events_dir.exists():
        raise FileNotFoundError(f"Missing events directory: {events_dir}")

    season_maps: Dict[str, np.ndarray] = {}
    season_summaries: Dict[str, Dict[str, float]] = {}
    season_livetimes: Dict[str, float] = {}

    combined = np.zeros((len(cfg.energy_edges_GeV) - 1, hp.nside2npix(cfg.nside)), dtype=np.int64)

    for season in cfg.seasons:
        ev_file = events_dir / _season_event_filename(season)
        if not ev_file.exists():
            print(f"[warn] missing season file, skipping: {ev_file}", file=sys.stderr)
            continue

        print(f"[info] Processing season={season} file={ev_file}")
        m, summ = _bin_events_to_map(ev_file, cfg)
        combined += m

        if per_season:
            season_maps[season] = m
            season_summaries[season] = summ

        season_livetimes[season] = _load_livetime_days(uptime_dir / _season_uptime_filename(season))

    global_summary = {
        "nside": int(cfg.nside),
        "nest": bool(cfg.nest),
        "n_pix": int(hp.nside2npix(cfg.nside)),
        "n_energy_bins": int(len(cfg.energy_edges_GeV) - 1),
        "seasons_requested": list(cfg.seasons),
        "seasons_found": list(season_livetimes.keys()),
        "livetime_days_total": float(np.nansum(list(season_livetimes.values()))),
    }

    _ensure_dir(output_npz)

    out = {
        "counts_map": combined,
        "E_edges_GeV": cfg.energy_edges_GeV,
        "nside": np.int64(cfg.nside),
        "nest": np.bool_(cfg.nest),
        "seasons_found": np.array(list(season_livetimes.keys()), dtype="U"),
        "season_livetime_days": np.array([season_livetimes[s] for s in season_livetimes.keys()], dtype=float),
        "global_summary_json": np.array(json.dumps(global_summary), dtype="U"),
    }

    if per_season:
        for season, m in season_maps.items():
            out[f"counts_map__{season}"] = m
            out[f"summary_json__{season}"] = np.array(json.dumps(season_summaries[season]), dtype="U")

    np.savez_compressed(output_npz, **out)

    sidecar = output_npz.with_suffix(".summary.json")
    with open(sidecar, "w", encoding="utf-8") as f:
        json.dump(
            {
                "global": global_summary,
                "season_livetime_days": season_livetimes,
                "notes": {
                    "energy_edges_GeV": cfg.energy_edges_GeV.tolist(),
                    "counts_map_shape": list(combined.shape),
                    "counts_map_dtype": str(combined.dtype),
                },
            },
            f,
            indent=2,
            sort_keys=True,
        )

    print(f"[done] Wrote maps: {output_npz}")
    print(f"[done] Wrote summary: {sidecar}")


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="Convert IceCube 10-year public point-source events (2008–2018) to multi-energy HEALPix counts maps.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--data-dir", type=str, default=DEFAULT_DATA_DIR)
    p.add_argument("--release-root", type=str, default="")
    p.add_argument("--zip-path", type=str, default="")
    p.add_argument("--auto-unzip", action="store_true")
    p.add_argument("--force-unzip", action="store_true")
    p.add_argument("--nside", type=int, default=512)
    p.add_argument("--nest", action="store_true")
    p.add_argument("--energy-edges", type=str, default="logspace:4,7,6")
    p.add_argument("--seasons", type=str, default=",".join(DEFAULT_SEASONS))
    p.add_argument("--chunk-size", type=int, default=1_000_000)
    p.add_argument("--per-season", action="store_true")
    p.add_argument("--output", type=str, default="outputs/real_data_maps/icecube10y_counts_maps.npz")

    args = p.parse_args(argv)

    data_dir = Path(args.data_dir).expanduser().resolve()

    if args.auto_unzip and args.zip_path:
        _maybe_unzip(Path(args.zip_path).expanduser().resolve(), data_dir, force=args.force_unzip)

    if args.release_root.strip():
        release_root = Path(args.release_root).expanduser().resolve()
    else:
        release_root = _find_release_root(data_dir, release_subdir=DEFAULT_RELEASE_SUBDIR)

    energy_edges = _parse_energy_edges(args.energy_edges)
    seasons = tuple([s.strip() for s in args.seasons.split(",") if s.strip()])

    build_maps(
        release_root=release_root,
        output_npz=Path(args.output).expanduser().resolve(),
        nside=args.nside,
        nest=args.nest,
        energy_edges_GeV=energy_edges,
        seasons=seasons,
        chunk_size=args.chunk_size,
        per_season=args.per_season,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
